from __future__ import annotations

import hashlib
import json
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "design/session-surface-contract.json"
EVIDENCE_ROOT = ROOT / "docs/evidence/v6/session"
SURFACES = {
    "sddm": ROOT / "sddm/NoxForge/Main.qml",
    "splash": ROOT
    / "look-and-feel/io.github.loofiboss.noxforge.desktop/contents/splash/Splash.qml",
    "logout": ROOT
    / "look-and-feel/io.github.loofiboss.noxforge.desktop/contents/logout/Logout.qml",
    "tabbox": ROOT
    / "kwin/tabbox/io.github.loofiboss.noxforge.desktop/contents/ui/Switcher.qml",
}
MOTION_POLICIES = (
    ROOT
    / "look-and-feel/io.github.loofiboss.noxforge.desktop/contents/splash/MotionPolicy.qml",
    ROOT
    / "look-and-feel/io.github.loofiboss.noxforge.desktop/contents/logout/MotionPolicy.qml",
    ROOT
    / "kwin/tabbox/io.github.loofiboss.noxforge.desktop/contents/ui/MotionPolicy.qml",
)


class V6PhaseFiveTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
        cls.manifest = json.loads(
            (EVIDENCE_ROOT / "manifest.json").read_text(encoding="utf-8")
        )

    def test_session_contract_has_complete_v6_matrices(self) -> None:
        self.assertEqual(self.contract["schemaVersion"], 2)
        self.assertEqual(set(self.contract["surfaces"]), set(SURFACES))
        self.assertEqual(
            {
                (size["width"], size["height"])
                for size in self.contract["v6ResolutionMatrix"]
            },
            {(1280, 720), (1920, 1080), (2560, 1440), (3440, 1440)},
        )
        scenarios = {
            scenario
            for surface_scenarios in self.contract["v6ScenarioMatrix"].values()
            for scenario in surface_scenarios
        }
        self.assertTrue(
            {"standard", "long-rtl", "keyboard", "empty", "error", "busy", "reduced"}
            <= scenarios
        )
        self.assertEqual(
            self.contract["choreographyFrames"],
            [
                {"name": "start", "progress": 0.0},
                {"name": "mid", "progress": 0.5},
                {"name": "end", "progress": 1.0},
            ],
        )
        self.assertFalse(self.contract["v6EvidencePolicy"]["qualifiesLiveSession"])

    def test_motion_policy_is_physical_generated_and_shared(self) -> None:
        payloads = []
        for path in MOTION_POLICIES:
            with self.subTest(path=path.relative_to(ROOT)):
                self.assertTrue(path.is_file())
                self.assertFalse(path.is_symlink())
                text = path.read_text(encoding="utf-8")
                self.assertIn("Generated by scripts/generate_design_system.py", text)
                self.assertIn("Kirigami.Units.shortDuration", text)
                self.assertIn("function duration(baseDuration)", text)
                self.assertIn("function segment(progress, start, end)", text)
                payloads.append(text)
        self.assertEqual(len(set(payloads)), 1)

        sddm = SURFACES["sddm"].read_text(encoding="utf-8")
        self.assertIn("import org.kde.kirigami.platform as Platform", sddm)
        self.assertIn("Platform.Units.shortDuration", sddm)
        self.assertNotIn("import org.kde.kirigami as Kirigami", sddm)

    def test_runtime_qml_uses_semantic_motion_and_test_progress_is_opt_in(self) -> None:
        combined = ""
        for surface, path in SURFACES.items():
            text = path.read_text(encoding="utf-8")
            combined += text
            with self.subTest(surface=surface):
                self.assertIn("property real testProgress: -1", text)
                self.assertIsNone(re.search(r"#[0-9A-Fa-f]{3,8}\b", text))
                self.assertIsNone(re.search(r"\bduration:\s*\d+", text))
                for curve in re.findall(r"easing\.bezierCurve:\s*([^\n]+)", text):
                    self.assertTrue(curve.strip().startswith("tokens."))
        self.assertIn("Behavior on", combined)
        self.assertIn("transitions: Transition", combined)

        renderer = (ROOT / "tools/session_renderer.cpp").read_text(encoding="utf-8")
        self.assertIn('setPropertyIfPresent(root, "testProgress", testProgress)', renderer)
        self.assertIn('scenario.endsWith(QStringLiteral("-start"))', renderer)
        self.assertIn('scenario.endsWith(QStringLiteral("-mid"))', renderer)
        self.assertIn('scenario.endsWith(QStringLiteral("-end"))', renderer)

    def test_runtime_session_contracts_and_model_roles_are_preserved(self) -> None:
        sddm = SURFACES["sddm"].read_text(encoding="utf-8")
        for required in (
            "sddm.login",
            "sessionModel",
            "keyboard.currentLayout",
            "sddm.suspend",
            "sddm.reboot",
            "sddm.powerOff",
            "onLoginFailed",
            "onLoginSucceeded",
            "KeyNavigation.tab",
        ):
            self.assertIn(required, sddm)
        self.assertIn("Layout.minimumHeight: 40", sddm)

        logout = SURFACES["logout"].read_text(encoding="utf-8")
        for signal in (
            "lockScreenRequested",
            "logoutRequested",
            "suspendRequested",
            "rebootRequested",
            "haltRequested",
            "cancelRequested",
        ):
            self.assertIn(signal, logout)
        self.assertNotIn("scale:", logout)

        tabbox = SURFACES["tabbox"].read_text(encoding="utf-8")
        for role in ("caption", "icon", "minimized"):
            self.assertIn(f"required property {'var' if role == 'icon' else 'bool' if role == 'minimized' else 'string'} {role}", tabbox)
        for unsupported in ("thumbnail", "windowGeometry", "desktopName"):
            self.assertNotIn(unsupported, tabbox)
        self.assertIn("windowList.contentHeight", tabbox)
        self.assertIn("ListView.Horizontal", tabbox)
        self.assertIn("ListView.Vertical", tabbox)

    def test_authentic_offscreen_evidence_is_complete_and_hash_bound(self) -> None:
        self.assertEqual(self.manifest["schemaVersion"], 1)
        self.assertEqual(self.manifest["captureCount"], 46)
        self.assertTrue(self.manifest["authenticQml"])
        self.assertFalse(self.manifest["liveSession"])
        self.assertEqual(self.manifest["reviewStatus"], "reviewed-offscreen")

        captures = self.manifest["captures"]
        self.assertEqual(len(captures), 46)
        choreography: dict[str, set[str]] = {}
        for capture in captures:
            path = EVIDENCE_ROOT / capture["file"]
            self.assertTrue(path.is_file())
            self.assertEqual(
                hashlib.sha256(path.read_bytes()).hexdigest(),
                capture["sha256"],
            )
            if capture["kind"] == "choreography":
                choreography.setdefault(capture["surface"], set()).add(capture["sha256"])
        self.assertEqual(set(choreography), set(SURFACES))
        self.assertTrue(all(len(hashes) == 3 for hashes in choreography.values()))

        for relative, digest in self.manifest["sourceHashes"].items():
            path = ROOT / relative
            self.assertTrue(path.is_file())
            self.assertEqual(hashlib.sha256(path.read_bytes()).hexdigest(), digest)

    def test_first_frame_gate_passes_against_v5(self) -> None:
        report = json.loads(
            (EVIDENCE_ROOT / "performance.json").read_text(encoding="utf-8")
        )
        self.assertEqual(report["phase"], 5)
        self.assertEqual(report["result"], "passed")
        self.assertEqual(report["maximumRatio"], 1.1)
        self.assertLessEqual(report["metric"]["ratio"], 1.1)
        self.assertEqual(len(report["metric"]["baselineSamplesMs"]), 11)
        self.assertEqual(len(report["metric"]["currentSamplesMs"]), 11)

    def test_live_session_cases_remain_blocked(self) -> None:
        qualification = json.loads(
            (ROOT / "docs/evidence/v6/qualification.json").read_text(encoding="utf-8")
        )
        live = {case["id"]: case for case in qualification["liveCases"]}
        for case_id in (
            "sddm-authentication-and-power",
            "logout-keyboard-and-pointer",
            "held-alt-tab",
        ):
            self.assertEqual(live[case_id]["status"], "blocked")
            self.assertIn("Phase 7", live[case_id]["reason"])


if __name__ == "__main__":
    unittest.main()
