// SPDX-License-Identifier: MIT
// Generated by scripts/generate_design_system.py. Do not edit directly.
import QtQuick
import org.kde.kirigami as Kirigami

QtObject {
    readonly property real durationScale: Kirigami.Units.shortDuration <= 0
        ? 0
        : Kirigami.Units.shortDuration / 100.0
    readonly property bool reducedMotion: durationScale <= 0

    function duration(baseDuration) {
        return reducedMotion ? 0 : Math.max(1, Math.round(baseDuration * durationScale))
    }

    function segment(progress, start, end) {
        if (end <= start) {
            return progress >= end ? 1 : 0
        }
        return Math.max(0, Math.min(1, (progress - start) / (end - start)))
    }
}
