-- SPDX-License-Identifier: MIT
-- Generated by scripts/generate_design_system.py for NoxForge Obsidian Neovim.
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "noxforge_obsidian"

local colors = {
  bg = "#000000",
  sunken = "#05080A",
  surface = "#0A0F13",
  border = "#2F414B",
  border_strong = "#455A64",
  fg = "#E8F0F2",
  fg_sec = "#A6B4B9",
  fg_dis = "#748289",
  accent = "#A3FF47",
  accent_soft = "#243528",
  cyan = "#22D3EE",
  violet = "#A78BFA",
  negative = "#FF6B7A",
  warning = "#FBBF24",
  keyword = "#A3FF47",
  func = "#E8F0F2",
  str = "#22D3EE",
  type = "#A78BFA",
  num = "#FBBF24",
  comment = "#748289",
  op = "#A6B4B9",
}

local highlights = {
  Normal = { fg = colors.fg, bg = colors.bg },
  NormalFloat = { fg = colors.fg, bg = colors.surface },
  FloatBorder = { fg = colors.border_strong, bg = colors.surface },
  ColorColumn = { bg = colors.sunken },
  Cursor = { fg = colors.bg, bg = colors.accent },
  CursorLine = { bg = colors.sunken },
  CursorColumn = { bg = colors.sunken },
  LineNr = { fg = colors.fg_dis },
  CursorLineNr = { fg = colors.accent, bold = true },
  VertSplit = { fg = colors.border, bg = colors.bg },
  WinSeparator = { fg = colors.border, bg = colors.bg },
  StatusLine = { fg = colors.fg, bg = colors.surface },
  StatusLineNC = { fg = colors.fg_sec, bg = colors.sunken },
  Pmenu = { fg = colors.fg, bg = colors.surface },
  PmenuSel = { fg = colors.fg, bg = colors.accent_soft, bold = true },
  PmenuSbar = { bg = colors.sunken },
  PmenuThumb = { bg = colors.border_strong },
  Visual = { bg = colors.accent_soft },
  Search = { fg = colors.bg, bg = colors.accent },
  IncSearch = { fg = colors.bg, bg = colors.accent },
  MatchParen = { fg = colors.accent, underline = true },
  Comment = { fg = colors.comment, italic = true },
  Constant = { fg = colors.num },
  String = { fg = colors.str },
  Character = { fg = colors.str },
  Number = { fg = colors.num },
  Boolean = { fg = colors.accent, bold = true },
  Float = { fg = colors.num },
  Identifier = { fg = colors.fg },
  Function = { fg = colors.func },
  Statement = { fg = colors.keyword, bold = true },
  Conditional = { fg = colors.keyword, bold = true },
  Repeat = { fg = colors.keyword, bold = true },
  Label = { fg = colors.keyword },
  Operator = { fg = colors.op },
  Keyword = { fg = colors.keyword, bold = true },
  Exception = { fg = colors.negative, bold = true },
  PreProc = { fg = colors.violet },
  Type = { fg = colors.type },
  Special = { fg = colors.cyan },
  Underlined = { underline = true },
  Error = { fg = colors.negative, bold = true },
  Todo = { fg = colors.accent, bold = true },
  DiagnosticError = { fg = colors.negative },
  DiagnosticWarn = { fg = colors.warning },
  DiagnosticInfo = { fg = colors.cyan },
  DiagnosticHint = { fg = colors.accent },
}

for group, opts in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, opts)
end
