// SPDX-License-Identifier: MIT
// Generated by scripts/generate_design_system.py. Do not edit directly.
import QtQuick 2.15

QtObject {
    readonly property color background: "#0E1318"
    readonly property color surface: "#141B21"
    readonly property color surfaceRaised: "#1A232B"
    readonly property color surfaceHover: "#202C34"
    readonly property color surfaceSelected: "#26361D"
    readonly property color border: "#2B3942"
    readonly property color borderStrong: "#3B4B55"
    readonly property color textPrimary: "#E8F0F2"
    readonly property color textSecondary: "#A6B4B9"
    readonly property color textDisabled: "#6F7C82"
    readonly property color accent: "#A3FF47"
    readonly property color accentPressed: "#82D936"
    readonly property color accentInk: "#0E1318"
    readonly property color detailCyan: "#22D3EE"
    readonly property color detailViolet: "#A78BFA"
    readonly property color negative: "#FF6B7A"
    readonly property color neutral: "#FBBF24"
    readonly property int radius: 6
    readonly property int compactRadius: 4
    readonly property int notch: 4
    readonly property int compactSpacing: 4
    readonly property int standardSpacing: 8
    readonly property int borderWidth: 1
    readonly property int focusWidth: 2
    readonly property int controlHeight: 32
    readonly property int largeControlHeight: 36
    readonly property int activeMarkerWidth: 3
    readonly property real disabledOpacity: 0.55
    readonly property int pressDuration: 90
    readonly property int hoverDuration: 140
    readonly property int popupDuration: 180
    readonly property int bodyWeight: 400
    readonly property int headingWeight: 600
    readonly property int brandTracking: 3
}
