[Icon Theme]
Name=NoxForge
Comment=Original Forge Identity system icons
Inherits=breeze-dark,breeze,hicolor
Directories=16x16/actions,16x16/applets,16x16/places,16x16/preferences,16x16/status,22x22/actions,22x22/applets,22x22/places,22x22/preferences,22x22/status,scalable/actions,scalable/applets,scalable/categories,scalable/devices,scalable/emblems,scalable/mimetypes,scalable/places,scalable/preferences,scalable/status

[16x16/actions]
Size=16
Context=Actions
Type=Fixed

[16x16/applets]
Size=16
Context=Applications
Type=Fixed

[16x16/status]
Size=16
Context=Status
Type=Fixed

[16x16/places]
Size=16
Context=Places
Type=Fixed

[16x16/preferences]
Size=16
Context=Categories
Type=Fixed

[22x22/actions]
Size=22
Context=Actions
Type=Fixed

[22x22/applets]
Size=22
Context=Applications
Type=Fixed

[22x22/status]
Size=22
Context=Status
Type=Fixed

[22x22/places]
Size=22
Context=Places
Type=Fixed

[22x22/preferences]
Size=22
Context=Categories
Type=Fixed

[scalable/actions]
Size=24
Context=Actions
Type=Scalable
MinSize=16
MaxSize=64

[scalable/places]
Size=24
Context=Places
Type=Scalable
MinSize=16
MaxSize=64

[scalable/devices]
Size=24
Context=Devices
Type=Scalable
MinSize=16
MaxSize=64

[scalable/status]
Size=24
Context=Status
Type=Scalable
MinSize=16
MaxSize=64

[scalable/applets]
Size=24
Context=Applications
Type=Scalable
MinSize=16
MaxSize=64

[scalable/categories]
Size=24
Context=Categories
Type=Scalable
MinSize=16
MaxSize=64

[scalable/emblems]
Size=24
Context=Emblems
Type=Scalable
MinSize=16
MaxSize=64

[scalable/mimetypes]
Size=24
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=64

[scalable/preferences]
Size=24
Context=Categories
Type=Scalable
MinSize=16
MaxSize=64
