#!/usr/bin/env python3
"""Generate NoxForge design-system consumers from the canonical token file."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS_PATH = ROOT / "design/tokens.json"
THEME_ID = "io.github.loofiboss.noxforge.desktop"

QML_TARGETS = (
    ROOT / f"look-and-feel/{THEME_ID}/contents/splash/Tokens.qml",
    ROOT / f"look-and-feel/{THEME_ID}/contents/logout/Tokens.qml",
    ROOT / f"kwin/tabbox/{THEME_ID}/contents/ui/Tokens.qml",
    ROOT / "sddm/NoxForge/Tokens.qml",
)

MARK_TARGETS = (
    ROOT / "design/brand/noxforge-mark.svg",
    ROOT / f"look-and-feel/{THEME_ID}/contents/splash/NoxForgeMark.svg",
    ROOT / f"look-and-feel/{THEME_ID}/contents/logout/NoxForgeMark.svg",
    ROOT / f"kwin/tabbox/{THEME_ID}/contents/ui/NoxForgeMark.svg",
    ROOT / "sddm/NoxForge/NoxForgeMark.svg",
)


def load_tokens() -> dict[str, object]:
    return json.loads(TOKENS_PATH.read_text(encoding="utf-8"))


def rgb(hex_color: str) -> str:
    return ",".join(str(int(hex_color[index : index + 2], 16)) for index in (1, 3, 5))


def cpp_header(tokens: dict[str, object]) -> str:
    colors = tokens["colors"]
    geometry = tokens["geometry"]
    states = tokens["states"]
    assert isinstance(colors, dict) and isinstance(geometry, dict) and isinstance(states, dict)
    functions = (
        ("background", "background"), ("surface", "surface"),
        ("surfaceRaised", "surfaceRaised"), ("surfaceHover", "surfaceHover"),
        ("surfaceSelected", "surfaceSelected"), ("border", "border"),
        ("borderStrong", "borderStrong"), ("textPrimary", "textPrimary"),
        ("textSecondary", "textSecondary"), ("textDisabled", "textDisabled"),
        ("accent", "accent"), ("accentPressed", "accentPressed"),
        ("cyan", "detailCyan"), ("violet", "detailViolet"),
        ("negative", "negative"), ("warning", "neutral"),
    )
    color_lines = "\n".join(
        f'inline QColor {name}() {{ return QColor(QStringLiteral("{colors[key]}")); }}'
        for name, key in functions
    )
    return f'''// SPDX-License-Identifier: MIT
// Generated by scripts/generate_design_system.py. Do not edit directly.
#pragma once

#include <QColor>

namespace NoxForgePalette {{

{color_lines}
inline QColor accentInk() {{ return background(); }}

constexpr int radius = {geometry["cornerRadius"]};
constexpr int compactRadius = {geometry["compactRadius"]};
constexpr int notch = {geometry["forgeNotch"]};
constexpr int borderWidth = {geometry["borderWidth"]};
constexpr int focusWidth = {geometry["focusWidth"]};
constexpr int controlHeight = {geometry["controlHeight"]};
constexpr int largeControlHeight = {geometry["largeControlHeight"]};
constexpr int activeMarkerWidth = {states["activeMarkerWidth"]};
constexpr qreal disabledOpacity = {states["disabledOpacity"]};

}} // namespace NoxForgePalette
'''


def qml_tokens(tokens: dict[str, object]) -> str:
    colors = tokens["colors"]
    geometry = tokens["geometry"]
    states = tokens["states"]
    motion = tokens["motion"]
    typography = tokens["typography"]
    assert all(isinstance(value, dict) for value in (colors, geometry, states, motion, typography))
    color_lines = "\n".join(
        f'    readonly property color {name}: "{value}"' for name, value in colors.items()
    )
    return f'''// SPDX-License-Identifier: MIT
// Generated by scripts/generate_design_system.py. Do not edit directly.
import QtQuick 2.15

QtObject {{
{color_lines}
    readonly property int radius: {geometry["cornerRadius"]}
    readonly property int compactRadius: {geometry["compactRadius"]}
    readonly property int notch: {geometry["forgeNotch"]}
    readonly property int compactSpacing: {geometry["compactSpacing"]}
    readonly property int standardSpacing: {geometry["standardSpacing"]}
    readonly property int borderWidth: {geometry["borderWidth"]}
    readonly property int focusWidth: {geometry["focusWidth"]}
    readonly property int controlHeight: {geometry["controlHeight"]}
    readonly property int largeControlHeight: {geometry["largeControlHeight"]}
    readonly property int activeMarkerWidth: {states["activeMarkerWidth"]}
    readonly property real disabledOpacity: {states["disabledOpacity"]}
    readonly property int pressDuration: {motion["pressMs"]}
    readonly property int hoverDuration: {motion["hoverMs"]}
    readonly property int popupDuration: {motion["popupMs"]}
    readonly property int bodyWeight: {typography["bodyWeight"]}
    readonly property int headingWeight: {typography["headingWeight"]}
    readonly property int brandTracking: {typography["brandTracking"]}
}}
'''


def brand_mark(tokens: dict[str, object]) -> str:
    colors = tokens["colors"]
    assert isinstance(colors, dict)
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="192" height="144" viewBox="0 0 192 144">
  <title>NoxForge angled N/F mark</title>
  <g fill="none" stroke-linecap="square" stroke-linejoin="miter">
    <path d="M20 116L48 28l52 78 28-78" stroke="{colors['textPrimary']}" stroke-width="16"/>
    <path d="M116 116l28-88h40M134 68h36" stroke="{colors['textPrimary']}" stroke-width="16"/>
    <path d="M46 28l54 78" stroke="{colors['accent']}" stroke-width="7"/>
    <path d="M144 28h40" stroke="{colors['accent']}" stroke-width="7"/>
  </g>
</svg>
'''


def color_scheme(tokens: dict[str, object]) -> str:
    colors = tokens["colors"]
    assert isinstance(colors, dict)
    roles = {
        "BackgroundAlternate": colors["surface"],
        "BackgroundNormal": colors["surfaceRaised"],
        "DecorationFocus": colors["accent"],
        "DecorationHover": colors["detailCyan"],
        "ForegroundActive": colors["accent"],
        "ForegroundInactive": colors["textSecondary"],
        "ForegroundLink": colors["detailCyan"],
        "ForegroundNegative": colors["negative"],
        "ForegroundNeutral": colors["neutral"],
        "ForegroundNormal": colors["textPrimary"],
        "ForegroundPositive": colors["accent"],
        "ForegroundVisited": colors["detailViolet"],
    }

    def section(name: str, background: str, alternate: str | None = None) -> str:
        section_roles = dict(roles)
        section_roles["BackgroundNormal"] = background
        section_roles["BackgroundAlternate"] = alternate or colors["surface"]
        body = "\n".join(f"{key}={rgb(str(value))}" for key, value in section_roles.items())
        return f"[{name}]\n{body}\n"

    return f'''# SPDX-FileCopyrightText: 2026 Loofi
# SPDX-License-Identifier: MIT

[ColorEffects:Disabled]
Color=70,79,86
ColorAmount=0
ColorEffect=0
ContrastAmount=0.55
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color={rgb(str(colors["textSecondary"]))}
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

{section("Colors:Button", str(colors["surfaceRaised"]))}
{section("Colors:Complementary", str(colors["background"]))}
{section("Colors:Header", str(colors["surfaceRaised"]))}
{section("Colors:Header][Inactive", str(colors["background"]))}
{section("Colors:Selection", str(colors["surfaceSelected"]), str(colors["surfaceSelected"]))}
{section("Colors:Tooltip", str(colors["surfaceRaised"]))}
{section("Colors:View", str(colors["background"]))}
{section("Colors:Window", str(colors["surface"]), str(colors["surfaceRaised"]))}
[General]
ColorScheme=NoxForgeDark
Name=NoxForge Dark
shadeSortColumn=true

[KDE]
contrast=4

[WM]
activeBackground={rgb(str(colors["surface"]))}
activeBlend={rgb(str(colors["accent"]))}
activeForeground={rgb(str(colors["textPrimary"]))}
inactiveBackground={rgb(str(colors["background"]))}
inactiveBlend={rgb(str(colors["textSecondary"]))}
inactiveForeground={rgb(str(colors["textSecondary"]))}
'''


def outputs(tokens: dict[str, object]) -> dict[Path, str]:
    colors_text = color_scheme(tokens)
    generated = {
        ROOT / "src/style/noxforgepalette.h": cpp_header(tokens),
        ROOT / "color-schemes/NoxForgeDark.colors": colors_text,
        ROOT / f"plasma/desktoptheme/{THEME_ID}/colors": colors_text,
    }
    qml = qml_tokens(tokens)
    generated.update({path: qml for path in QML_TARGETS})
    mark = brand_mark(tokens)
    generated.update({path: mark for path in MARK_TARGETS})
    return generated


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files drift")
    args = parser.parse_args()
    generated = outputs(load_tokens())
    drift: list[str] = []
    for path, content in generated.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if drift:
        print("generated design consumers are stale: " + ", ".join(drift), file=sys.stderr)
        return 1
    if not args.check:
        print(f"Generated {len(generated)} design-system consumers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
