#!/usr/bin/env python3
"""Generate NoxForge design-system consumers from the canonical token file."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS_PATH = ROOT / "design/tokens.json"
THEME_ID = "io.github.loofiboss.noxforge.desktop"

QML_TARGETS = (
    ROOT / f"look-and-feel/{THEME_ID}/contents/splash/Tokens.qml",
    ROOT / f"look-and-feel/{THEME_ID}/contents/logout/Tokens.qml",
    ROOT / f"kwin/tabbox/{THEME_ID}/contents/ui/Tokens.qml",
    ROOT / "sddm/NoxForge/Tokens.qml",
)

MOTION_POLICY_TARGETS = (
    ROOT / f"look-and-feel/{THEME_ID}/contents/splash/MotionPolicy.qml",
    ROOT / f"look-and-feel/{THEME_ID}/contents/logout/MotionPolicy.qml",
    ROOT / f"kwin/tabbox/{THEME_ID}/contents/ui/MotionPolicy.qml",
)

MARK_TARGETS = (
    ROOT / "design/brand/noxforge-mark.svg",
    ROOT / f"look-and-feel/{THEME_ID}/contents/splash/NoxForgeMark.svg",
    ROOT / f"look-and-feel/{THEME_ID}/contents/logout/NoxForgeMark.svg",
    ROOT / f"kwin/tabbox/{THEME_ID}/contents/ui/NoxForgeMark.svg",
    ROOT / "sddm/NoxForge/NoxForgeMark.svg",
)

LOCKUP_TARGETS = (
    ROOT / "design/brand/noxforge-lockup.svg",
    ROOT / f"look-and-feel/{THEME_ID}/contents/splash/NoxForgeLockup.svg",
    ROOT / "sddm/NoxForge/NoxForgeLockup.svg",
)

MONO_MARK_TARGET = ROOT / "design/brand/noxforge-mark-mono.svg"


def load_tokens() -> dict[str, object]:
    return json.loads(TOKENS_PATH.read_text(encoding="utf-8"))


def rgb(hex_color: str) -> str:
    return ",".join(str(int(hex_color[index : index + 2], 16)) for index in (1, 3, 5))


def canonical_tokens(tokens: dict[str, object]) -> str:
    return json.dumps(tokens, ensure_ascii=True, separators=(",", ":"), sort_keys=True)


def cpp_header(tokens: dict[str, object]) -> str:
    colors = tokens["colors"]
    geometry = tokens["geometry"]
    opacity = tokens["opacity"]
    overlay = tokens["overlay"]
    shadow = tokens["shadow"]
    states = tokens["states"]
    motion = tokens["motion"]
    assert all(
        isinstance(value, dict)
        for value in (colors, geometry, opacity, overlay, shadow, states, motion)
    )
    reduced_motion = motion["reducedMotion"]
    assert isinstance(reduced_motion, dict)
    functions = (
        ("background", "background"), ("surfaceSunken", "surfaceSunken"),
        ("surface", "surface"), ("surfaceRaised", "surfaceRaised"),
        ("surfaceOverlay", "surfaceOverlay"), ("surfaceHover", "surfaceHover"),
        ("surfaceSelected", "surfaceSelected"), ("border", "border"),
        ("borderStrong", "borderStrong"), ("edgeHighlight", "edgeHighlight"),
        ("outlineMuted", "outlineMuted"), ("textPrimary", "textPrimary"),
        ("textSecondary", "textSecondary"), ("textDisabled", "textDisabled"),
        ("accent", "accent"), ("accentPressed", "accentPressed"),
        ("accentSoft", "accentSoft"), ("accentMuted", "accentMuted"),
        ("cyan", "detailCyan"), ("violet", "detailViolet"),
        ("negative", "negative"), ("warning", "neutral"),
    )
    color_lines = "\n".join(
        f'inline QColor {name}() {{ return QColor(QStringLiteral("{colors[key]}")); }}'
        for name, key in functions
    )
    return f'''// SPDX-License-Identifier: MIT
// Generated by scripts/generate_design_system.py. Do not edit directly.
#pragma once

#include <QByteArray>
#include <QColor>

namespace NoxForgePalette {{

{color_lines}
inline QColor accentInk() {{ return background(); }}

constexpr int radius = {geometry["cornerRadius"]};
constexpr int compactRadius = {geometry["compactRadius"]};
constexpr int overlayRadius = {geometry["overlayRadius"]};
constexpr int notch = {geometry["forgeNotch"]};
constexpr int borderWidth = {geometry["borderWidth"]};
constexpr int focusWidth = {geometry["focusWidth"]};
constexpr int controlHeight = {geometry["controlHeight"]};
constexpr int largeControlHeight = {geometry["largeControlHeight"]};
constexpr int activeMarkerWidth = {states["activeMarkerWidth"]};
constexpr qreal disabledOpacity = {opacity["disabled"]};
constexpr qreal enabledOpacity = {opacity["enabled"]};
constexpr qreal inactiveOpacity = {opacity["inactive"]};
constexpr qreal subtleOpacity = {opacity["subtle"]};
constexpr qreal scrimOpacity = {opacity["scrim"]};
constexpr qreal hoverOverlayOpacity = {overlay["hover"]["opacity"]};
constexpr qreal pressedOverlayOpacity = {overlay["pressed"]["opacity"]};
constexpr qreal busyOverlayOpacity = {overlay["busy"]["opacity"]};
constexpr int controlShadowOffsetY = {shadow["ambient"]["offsetY"]};
constexpr int controlShadowBlurRadius = {shadow["ambient"]["blurRadius"]};
constexpr qreal controlShadowOpacity = {shadow["ambient"]["opacity"]};
constexpr int popupShadowOffsetY = {shadow["overlay"]["offsetY"]};
constexpr int popupShadowBlurRadius = {shadow["overlay"]["blurRadius"]};
constexpr qreal popupShadowOpacity = {shadow["overlay"]["opacity"]};
constexpr int instantDuration = {motion["instantMs"]};
constexpr int pressDuration = {motion["pressMs"]};
constexpr int productiveDuration = {motion["productiveMs"]};
constexpr int selectionDuration = {motion["selectionMs"]};
constexpr int containerDuration = {motion["containerMs"]};
constexpr int expressiveDuration = {motion["expressiveMs"]};
constexpr int staggerDuration = {motion["staggerMs"]};
constexpr int busyCycleDuration = {motion["busyCycleMs"]};
constexpr int reducedMotionDuration = {reduced_motion["durationMs"]};
constexpr bool reducedSpatialMotion = {str(reduced_motion["spatialMotion"]).lower()};
constexpr bool reducedBusyIndicatorStatic = {str(reduced_motion["busyIndicatorStatic"]).lower()};

inline QByteArray canonicalTokensJson()
{{
    return QByteArrayLiteral(R"noxforge({canonical_tokens(tokens)})noxforge");
}}

}} // namespace NoxForgePalette
'''


def qml_tokens(tokens: dict[str, object]) -> str:
    colors = tokens["colors"]
    geometry = tokens["geometry"]
    opacity = tokens["opacity"]
    overlay = tokens["overlay"]
    shadow = tokens["shadow"]
    states = tokens["states"]
    motion = tokens["motion"]
    typography = tokens["typography"]
    assert all(
        isinstance(value, dict)
        for value in (colors, geometry, opacity, overlay, shadow, states, motion, typography)
    )
    reduced_motion = motion["reducedMotion"]
    typography_roles = typography["roles"]
    curves = motion["curves"]
    assert all(
        isinstance(value, dict)
        for value in (reduced_motion, typography_roles, curves)
    )
    color_lines = "\n".join(
        f'    readonly property color {name}: "{value}"' for name, value in colors.items()
    )
    return f'''// SPDX-License-Identifier: MIT
// Generated by scripts/generate_design_system.py. Do not edit directly.
import QtQuick 2.15

QtObject {{
{color_lines}
    readonly property int radius: {geometry["cornerRadius"]}
    readonly property int compactRadius: {geometry["compactRadius"]}
    readonly property int overlayRadius: {geometry["overlayRadius"]}
    readonly property int notch: {geometry["forgeNotch"]}
    readonly property int compactSpacing: {geometry["compactSpacing"]}
    readonly property int standardSpacing: {geometry["standardSpacing"]}
    readonly property int borderWidth: {geometry["borderWidth"]}
    readonly property int focusWidth: {geometry["focusWidth"]}
    readonly property int controlHeight: {geometry["controlHeight"]}
    readonly property int largeControlHeight: {geometry["largeControlHeight"]}
    readonly property int activeMarkerWidth: {states["activeMarkerWidth"]}
    readonly property real disabledOpacity: {opacity["disabled"]}
    readonly property real enabledOpacity: {opacity["enabled"]}
    readonly property real inactiveOpacity: {opacity["inactive"]}
    readonly property real subtleOpacity: {opacity["subtle"]}
    readonly property real scrimOpacity: {opacity["scrim"]}
    readonly property color hoverOverlayColor: "{colors[overlay["hover"]["color"]]}"
    readonly property real hoverOverlayOpacity: {overlay["hover"]["opacity"]}
    readonly property color pressedOverlayColor: "{colors[overlay["pressed"]["color"]]}"
    readonly property real pressedOverlayOpacity: {overlay["pressed"]["opacity"]}
    readonly property color busyOverlayColor: "{colors[overlay["busy"]["color"]]}"
    readonly property real busyOverlayOpacity: {overlay["busy"]["opacity"]}
    readonly property int controlShadowOffsetY: {shadow["ambient"]["offsetY"]}
    readonly property int controlShadowBlurRadius: {shadow["ambient"]["blurRadius"]}
    readonly property real controlShadowOpacity: {shadow["ambient"]["opacity"]}
    readonly property int popupShadowOffsetY: {shadow["overlay"]["offsetY"]}
    readonly property int popupShadowBlurRadius: {shadow["overlay"]["blurRadius"]}
    readonly property real popupShadowOpacity: {shadow["overlay"]["opacity"]}
    readonly property int instantDuration: {motion["instantMs"]}
    readonly property int pressDuration: {motion["pressMs"]}
    readonly property int productiveDuration: {motion["productiveMs"]}
    readonly property int selectionDuration: {motion["selectionMs"]}
    readonly property int containerDuration: {motion["containerMs"]}
    readonly property int expressiveDuration: {motion["expressiveMs"]}
    readonly property int staggerDuration: {motion["staggerMs"]}
    readonly property int busyCycleDuration: {motion["busyCycleMs"]}
    readonly property int hoverDuration: productiveDuration
    readonly property int popupDuration: containerDuration
    readonly property int busyDuration: busyCycleDuration
    readonly property list<real> productiveEnterCurve: {json.dumps(curves["productiveEnter"])}
    readonly property list<real> standardCurve: {json.dumps(curves["standard"])}
    readonly property list<real> exitCurve: {json.dumps(curves["exit"])}
    readonly property list<real> expressiveCurve: {json.dumps(curves["expressive"])}
    readonly property int reducedMotionDuration: {reduced_motion["durationMs"]}
    readonly property bool reducedSpatialMotion: {str(reduced_motion["spatialMotion"]).lower()}
    readonly property bool reducedBusyIndicatorStatic: {str(reduced_motion["busyIndicatorStatic"]).lower()}
    readonly property bool reducedOpacityTransitions: {str(reduced_motion["opacityTransitions"]).lower()}
    readonly property int bodyWeight: {typography_roles["body"]["weight"]}
    readonly property int headingWeight: {typography_roles["sectionTitle"]["weight"]}
    readonly property int displayClockSize: {typography_roles["displayClock"]["pixelSize"]}
    readonly property int surfaceTitleSize: {typography_roles["surfaceTitle"]["pixelSize"]}
    readonly property int sectionTitleSize: {typography_roles["sectionTitle"]["pixelSize"]}
    readonly property int bodySize: {typography_roles["body"]["pixelSize"]}
    readonly property int controlLabelSize: {typography_roles["controlLabel"]["pixelSize"]}
    readonly property int metadataSize: {typography_roles["metadata"]["pixelSize"]}
    readonly property int microLabelSize: {typography_roles["microLabel"]["pixelSize"]}
    readonly property int brandTracking: {typography["brandTracking"]}
    readonly property string canonicalTokensJson: '{canonical_tokens(tokens)}'
}}
'''


def qml_motion_policy() -> str:
    return '''// SPDX-License-Identifier: MIT
// Generated by scripts/generate_design_system.py. Do not edit directly.
import QtQuick
import org.kde.kirigami as Kirigami

QtObject {
    readonly property real durationScale: Kirigami.Units.shortDuration <= 0
        ? 0
        : Kirigami.Units.shortDuration / 100.0
    readonly property bool reducedMotion: durationScale <= 0

    function duration(baseDuration) {
        return reducedMotion ? 0 : Math.max(1, Math.round(baseDuration * durationScale))
    }

    function segment(progress, start, end) {
        if (end <= start) {
            return progress >= end ? 1 : 0
        }
        return Math.max(0, Math.min(1, (progress - start) / (end - start)))
    }
}
'''


def brand_mark(tokens: dict[str, object]) -> str:
    colors = tokens["colors"]
    assert isinstance(colors, dict)
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="192" height="144" viewBox="0 0 192 144">
  <title>NoxForge Kinetic Precision N/F mark</title>
  <g fill="none" stroke-linecap="square" stroke-linejoin="miter">
    <path d="M18 116L46 28l62 88 28-88h48M123 70h45"
          stroke="{colors['textPrimary']}" stroke-width="14"/>
    <path d="M47 30l59 84M136 28h48"
          stroke="{colors['accent']}" stroke-width="4"/>
  </g>
</svg>
'''


def monochrome_brand_mark(tokens: dict[str, object]) -> str:
    colors = tokens["colors"]
    assert isinstance(colors, dict)
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="192" height="144" viewBox="0 0 192 144">
  <title>NoxForge Kinetic Precision monochrome N/F mark</title>
  <path d="M18 116L46 28l62 88 28-88h48M123 70h45"
        fill="none" stroke="{colors['textPrimary']}" stroke-width="14"
        stroke-linecap="square" stroke-linejoin="miter"/>
</svg>
'''


def brand_lockup(tokens: dict[str, object]) -> str:
    colors = tokens["colors"]
    assert isinstance(colors, dict)
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="600" height="144" viewBox="0 0 600 144">
  <title>NoxForge Kinetic Precision horizontal lockup</title>
  <g fill="none" stroke-linecap="square" stroke-linejoin="miter">
    <path d="M18 116L46 28l62 88 28-88h48M123 70h45"
          stroke="{colors['textPrimary']}" stroke-width="14"/>
    <path d="M47 30l59 84M136 28h48"
          stroke="{colors['accent']}" stroke-width="4"/>
  </g>
  <g transform="translate(216 46)" fill="none" stroke="{colors['textPrimary']}"
     stroke-width="5" stroke-linecap="square" stroke-linejoin="miter">
    <path d="M0 52V0l28 52V0"/>
    <path d="M44 0h28v52H44z"/>
    <path d="M88 0l28 52M116 0L88 52"/>
    <path d="M132 52V0h30M132 25h24"/>
    <path d="M178 0h28v52h-28z"/>
    <path d="M222 52V0h28l8 8v14l-8 8h-28M244 30l16 22"/>
    <path d="M304 8l-8-8h-20v52h28V30h-14"/>
    <path d="M320 0h30M320 0v52h30M320 25h24"/>
  </g>
</svg>
'''


def color_scheme(tokens: dict[str, object]) -> str:
    colors = tokens["colors"]
    assert isinstance(colors, dict)
    roles = {
        "BackgroundAlternate": colors["surface"],
        "BackgroundNormal": colors["surfaceRaised"],
        "DecorationFocus": colors["accent"],
        "DecorationHover": colors["detailCyan"],
        "ForegroundActive": colors["accent"],
        "ForegroundInactive": colors["textSecondary"],
        "ForegroundLink": colors["detailCyan"],
        "ForegroundNegative": colors["negative"],
        "ForegroundNeutral": colors["neutral"],
        "ForegroundNormal": colors["textPrimary"],
        "ForegroundPositive": colors["accent"],
        "ForegroundVisited": colors["detailViolet"],
    }

    def section(name: str, background: str, alternate: str | None = None) -> str:
        section_roles = dict(roles)
        section_roles["BackgroundNormal"] = background
        section_roles["BackgroundAlternate"] = alternate or colors["surface"]
        body = "\n".join(f"{key}={rgb(str(value))}" for key, value in section_roles.items())
        return f"[{name}]\n{body}\n"

    return f'''# SPDX-FileCopyrightText: 2026 Loofi
# SPDX-License-Identifier: MIT

[ColorEffects:Disabled]
Color=70,79,86
ColorAmount=0
ColorEffect=0
ContrastAmount=0.55
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color={rgb(str(colors["textSecondary"]))}
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

{section("Colors:Button", str(colors["surfaceRaised"]))}
{section("Colors:Complementary", str(colors["background"]))}
{section("Colors:Header", str(colors["surfaceRaised"]))}
{section("Colors:Header][Inactive", str(colors["background"]))}
{section("Colors:Selection", str(colors["surfaceSelected"]), str(colors["surfaceSelected"]))}
{section("Colors:Tooltip", str(colors["surfaceRaised"]))}
{section("Colors:View", str(colors["background"]))}
{section("Colors:Window", str(colors["surface"]), str(colors["surfaceRaised"]))}
[General]
ColorScheme=NoxForgeDark
Name=NoxForge Dark
shadeSortColumn=true

[KDE]
contrast=4

[WM]
activeBackground={rgb(str(colors["surface"]))}
activeBlend={rgb(str(colors["accent"]))}
activeForeground={rgb(str(colors["textPrimary"]))}
inactiveBackground={rgb(str(colors["background"]))}
inactiveBlend={rgb(str(colors["textSecondary"]))}
inactiveForeground={rgb(str(colors["textSecondary"]))}
'''


def outputs(tokens: dict[str, object]) -> dict[Path, str]:
    colors_text = color_scheme(tokens)
    generated = {
        ROOT / "src/style/noxforgepalette.h": cpp_header(tokens),
        ROOT / "color-schemes/NoxForgeDark.colors": colors_text,
        ROOT / f"plasma/desktoptheme/{THEME_ID}/colors": colors_text,
    }
    qml = qml_tokens(tokens)
    generated.update({path: qml for path in QML_TARGETS})
    motion_policy = qml_motion_policy()
    generated.update({path: motion_policy for path in MOTION_POLICY_TARGETS})
    mark = brand_mark(tokens)
    generated.update({path: mark for path in MARK_TARGETS})
    generated[MONO_MARK_TARGET] = monochrome_brand_mark(tokens)
    lockup = brand_lockup(tokens)
    generated.update({path: lockup for path in LOCKUP_TARGETS})
    return generated


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files drift")
    args = parser.parse_args()
    generated = outputs(load_tokens())
    drift: list[str] = []
    for path, content in generated.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if drift:
        print("generated design consumers are stale: " + ", ".join(drift), file=sys.stderr)
        return 1
    if not args.check:
        print(f"Generated {len(generated)} design-system consumers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
